name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
      - uses: nrwl/nx-set-shas@v4.0.0
      - run: npm ci --legacy-peer-deps --include=optional
      - run: npm run build-rxjs
        with:
          working-directory: rxjs
      - run: pwd
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - name: Install
        run: npm ci --legacy-peer-deps --include=optional
        working-directory: ./angular-workspace
      - name: Build
        run: npm run build-rxjs
        working-directory: ./angular-workspace
      - name: Publish
        run: npm publish --access public
        working-directory: ./angular-workspace/libs/rxjs
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
